default: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/development.sqlite3

production:
  <<: *default
  database: db/development.sqlite3